spring.application.name=AiStudyAgentBackend
# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# H2 DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=//oppoA11K

# ===============================
# H2 CONSOLE (for browser access)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# LOGGING (optional)
# ===============================
logging.level.org.springframework=INFO



# Ollama Config
ollama.url=http://localhost:11434/api/generate
ollama.model=gpt-oss:20b-cloud

